### ISSUE TITLE
SRG Page view tracking support

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#108]
**As a user** I want to be able to easily implement page view tracking in my application.

# Acceptance criteria

- Automatic view tracking is possible (Fragment / Activity).
- Page view analytics are correctly collected in the demo.

# Tasks

- [x] Implement view tracking api for Fragment / Activity.
- [x] Support lifecycle events automatically.
- [x] Implement in demo.

**Comment by StaehliJ** [comment]
Fragment automatic tracking won't be implemented. Multiple fragment can be visible at the same time, it is too difficult to automatise this aspect, integrators knows best when and how to do their page views.

**Comment by StaehliJ** [comment]
With lifecycle process we can listen when application/process is in foreground or in background. Very useful to send again a page view when coming back to foreground.
