### ISSUE TITLE
Integrate Integration layer demo

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#116]
**As a user/integrator** I can try content from integration layer.

# Acceptance criteria

- Add UI to retrive integration layer medias.
- Every BU can be tested (SWI, RTS, SRF, RSI, RTR).

# Tasks

- [x] Add bottom navigation destination "Lists".
- [x] Add Integration layer DataProvider from SRLetterbox .
- [x] TV Topics
- [x] TV Latest video
- [x] TV Livestreams
- [x] TV Shows
- [x] Latest media from show urn
- [x] Live center
- [x] sport center (Live web)
- [x] Radio live stream
- [x] Radio Shows for each channel
- [x] Radio latest for each channel
- [x] Search tab with bu selector, only query string
- [ ] TextEdit for urn and url without DRM in top of first tab.

**Comment by StaehliJ** [comment]
No so simple, SRGLetterbox data layer is stored on a private repository
