### ISSUE TITLE
Fix flaky Tests on CI

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#120]
**As a Pillarbox developer ** I want to be able to merge PR without flaky tests.

# Acceptance criteria

- Test that should always pass always passes. No more flaky.

# Tasks

- [ ] Improve tests if possible
- [ ] Remove flaky tests when executing on the CI.
- [ ] Improve workflow with gradle cache and maven dependency cache

Hints : [cache](https://github.com/actions/setup-java#caching-packages-dependencies)
