### ISSUE TITLE
Add playback speed API

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#127]
**As a developer**, I want to be able to change the playback speed via an API.

# Acceptance criteria

- The API should provide a method/property to set the playback speed of the player.
- The playback speed can be adjusted to any float value >= 0.0f.
- The playback speed have to be kept after media transition.
- The playback speed rate is send to Commanders `media_playback_rate` when sending an event.
- The playback speed rate is notified to ComScore api at startup and when it's changing.
- Live content are treated like other content.

# Open question

- What happens with live only and live with dvr?
- What happens to live content between when changing playback speed rate before?

# Tasks

- [x] Create a public method/property in the player class for changing the playback speed directly.
- [x] Update ComScore and CommandersAct MediaItemTracker
- [x] Add playback speed rate to the `PlayerState`
- [x] Add single choice playback speed rate (0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0)

**Comment by StaehliJ** [comment]
We could improve demo by using BottomSheet for playback options. But as we only have playback speed options it may be overkill and Compose integration may be tricky.
