### ISSUE TITLE
Playback speed for live content

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#131]
**As a user / integrator** I want to have a playback speed to 1x when playing at live edge.

# Acceptance criteria

- Playback speed automatically set to 1x when playing at live edge with speed > 1x.
- Set playback speed rate does not have effect at live edge if speed is > 1x.
- If a live is inside a playlist, the playback speed changes will be fixed for the next and previous items.

# Tasks

- [ ] Detect live edge position to change playback speed to 1.
- [ ] Override setPlaybackSpeedRate.
- [ ] Create an api to check if a given playback speed is available or not.
- [ ] Allows playback speed rate < 1 for live dvr.
- [ ] Investigate LiveConfiguration..

https://github.com/SRGSSR/pillarbox-apple/issues/367
