### ISSUE TITLE
Improve Player state flows

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#135]
**As a user / integrator**  I want to collect state flow easily and in a more robust way.

# Acceptance criteria

- PlayerState should not have `dispose` method and should not use a DisposableEffect.
- Use CallbackFlow to listen player state.

# Tasks

- [x] Remove DisposableEffect when using PlayerState
- [x] Migrate PlayerState with CallbackFlows
- [x] PlayerState should expose StateFlow
- [x] Rename Composable extension otherwise they will be shadowed by `Player` interface
- [x] Update Unit Tests

**Comment by StaehliJ** [comment]
The old `PlayerState` may override Player to have all player methods. But all the state field have to be renamed
- isPlayingFlow
- playbackStateFlow

As well as Compose extension with postfixing with State
- isPlayingState()
- playbackStateState() a bit wired?

**Comment by StaehliJ** [comment]
Delete old PlayerState as it is no more needed.
