### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#138]
Investigate [Android 14](https://developer.android.com/about/versions/14/behavior-changes-all) support.

# Tasks

- [x] update demo target sdk to 34.
- [ ] update demo min sdk to 23 instead of 21.
- [ ] check privacy manager.
- [ ] check fullscreen notification intent.

**Comment by StaehliJ** [comment]
It seems that application targeting api 34 on api 34 device cannot be installed if minSDK < 23 [source](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level)

**Comment by StaehliJ** [comment]
###  New permission needs to be added

` java.lang.SecurityException: Starting FGS with type mediaPlayback callerApp=ProcessRecord{c3870b1 5765:ch.srgssr.pillarbox.demo.debug/u0a182} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK] `

**Comment by StaehliJ** [comment]
### Ongoing dismissable notification changes

Now user can dismiss notification even if it is on going [source](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications).

In the demo, the media notification is displayed while playing content, user can dimiss the notification while playing and the media continue playing if no change is made.

**Comment by StaehliJ** [comment]
merge in https://github.com/SRGSSR/pillarbox-android/pull/256
