### ISSUE TITLE
Basic playback of a Swissinfo content in the demo app

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#14]
As a user I can play a Swissinfo content in the demo application with a minimalist user interface.

# Acceptance criteria

- The player plays the [following content](https://play.swissinfo.ch/play/tv/society/video/switzerland-says-sorry?urn=urn:swi:video:47459404).
- The demo application displays the video to the user.
- Playback starts without user intervention.
- The user can pause / resume playback with a button.
- The user can seek anywhere in the video with a slider.

# Tasks

- [x] Integrate _ExoPlayer_ in a `Player` as a wrapper.
- [x] Implement a one url data source that configure a `MediaItem` for _Exoplayer_.
- [x] Create a PlayerView in the demo using a default `ExoplayerView`.
- [x] Configure the player to start automatically.
- [x] Don't restart the playback on screen orientation change.
- [x] Pause playback when `DemoActivity` goes in background.
