### ISSUE TITLE
ComScore page view improvements

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#167]
**As a user / integrator** I want to setup and send page view Comscore has decided with MediaPulse.

### Label send for page view

Nothing more and nothing less! It means that levels and from push notification will be ignored.

| Label | Description |
| :---: | :--- |
| ns_ap_an | if Config.nonLocalizedApplicationName is null use the Comscore setup that is read from the package informations |
| mp_v | Version name retrieve from package informations |
| mp_brand | Bu distributor | 
| c8 | page title |

# Acceptance criteria

- Each comscore page view send at least those labels.
- mp_v label have to be the application version name define by the integrator.
- mp_brand is the bu distributor.
- ns_ap_an is correctly override when integrator is using `Config.nonLocalizedApplicationName `
- c8 with the page title set by the integrator

# Tasks

- [x] Change how `ns_ap_an` is overriden
- [x] Add c8 label
- [x] Remove `ns_category` 
- [x] Remove `srg_title`
- [x] Remove `name`
- [x] Remove `srg_n` levels
- [x] Remove `srg_ap_push`
