### ISSUE TITLE
Simplify SRGAnalytics initialization

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#171]
**As a user / integrator** I want to use SRGAnalytics the simplest way and make it testable.

Like Coil or other library that are using singleton, we can provide a default config or the configuration can be provided from a Application interface or from build settings.

# Acceptance criteria

- Configurations are in one class.
- SRGAnalytics can be testable.

# Tasks

- [x] Simplify configuration
- [x] Simplify or extend SRGAnalytics initialization
- [x] Rename `virtualSite` to `appSiteName` 
- [x] Update readme.MD

**Comment by StaehliJ** [comment]
Ghost start handle can be removed. We follow the official recommandation from ComScore to start the library in Application.onCreate().

**Comment by StaehliJ** [comment]
A nice addition could be

```kotlin
@SRGApplication(config = ...)
class MyApplication : Application{
...
}
```
