### ISSUE TITLE
Remove unused CommandersAct streaming label

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#174]
**As a developer** I want to keep analytics tight. `media_playback_rate` and `media_bandwidth` is not used by analytics teams and can therefore be dropped.

# Remark

**As SRF analytics team** member I might be interested to track playback speed feature usage, though. This can readily be achieved with events (e.g. in response to a button being pressed) instead of streaming events, which do not notify about speed changes anyway.

# Acceptance criteria

- `media_playback_rate` is not sent anymore in Commanders Act analytics.
- `media_bandwidth` is not sent anymore in Commanders Act analytics
- Set device volume also to 0 if player volume is 0.
- Don't start uptime when current item is not a live stream.

# Tasks

- [x] Remove `media_playback_rate`.
- [x] Remove `media_bandwidth`.
- [x] Send 0 to device volume if player is muted.
- [x] Start uptime heart beat only for live item.
- [x] Remove time shift live threshold, for live stream always send the current time shift
