### ISSUE TITLE
Improve page view and event APIs

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#182]
**As a GD analyst** I would like data to be sent according to [official specifications](https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=13188782). **As Mediapulse analyst** I want the same, with [dedicated specifications[(https://ktglbuc.sharepoint.com/sites/TechGroupMediapulseOnlineData). **As BU analyst** I want optional data to be sendable as well for page views and events.

# Acceptance criteria

- Requirements listed above have been implemented.
- APIs provide proper types to fill comScore and Commanders Act data in a way that clearly identifies which data goes to which service.
- The page view and event APIs for Commanders Act accept additional labels in a flexible way.

# Tasks

## General

- [x] Update page view and event APIs to accept data explicitly tailored for comScore, resp. Commanders Act, in a single call.
- [x] Update demo.
- [x] Update documentation.

## comScore

- [x] Add open page view label dictionary and ensure correct merge with official labels.

## Commanders Act

- [x] Send name in `page_name` (replaces `content_title`).
- [x] Send type in `page_type` (replaces `content_page_type`). 
- [x] Add other page view parameters from [the specifications](https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=13188782). Remark: `page_id` does not seem mandatory.
- [x] Add other event parameters from [the specifications](https://confluence.srg.beecollaboration.com/pages/viewpage.action?pageId=13188782).
- [ ] Add open page view label dictionary and ensure correct merge with official labels.
- [ ] Add open event label dictionary and ensure correct merge with official labels.

### Hint

Required are probably only title, levels and type.
