### ISSUE TITLE
POC : Update MediaItem during playback

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#19]
As a user update sometimes the content during playback so I can display updated metadata information to the UI. 

# Acceptance criteria

- The data source expose a Flow of data.
- Data changes are metadata only.
- No change of other parameters if relevant.
- No need to handle Uri changes, let assume for the scope of this story that the Uri is constant.

# Tasks

- [ ] Adapte MediaSource to retrun a Flow
- [ ] Handle change in MediaSource
- [ ] Add test case in the demo
