### ISSUE TITLE
PoC : Tracks management

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#193]
# Goals
Understand that the `DefaultTrackSelector`  can or can't do without modifications.

# Tasks

- [ ] Displays audio tracks selections.
- [ ] Displays video tracks selections.
- [ ] Displays subtitles selections.
- [ ] Handle accessibility settings.
- [ ] Handle forced subtitles.

**Comment by StaehliJ** [comment]
## Forced subtitles

Forced subtitles have to be selected when user doesn't want subtitles. The selected forced subtitle language have to match the selected audio language.

### Problems

- `DefaultTrackSelector` apply track override at the very end of the selection process. 
- If the user disable the text track with `TrackSelectionParameters.setTrackTypeDisabled` it would deselect all text track, even forced one.

**Comment by StaehliJ** [comment]
## Default subtitles

If the playlist have marked a text track with selection flag = auto or/and default. It will automatically selected the default one. Even if the user changes audio language preferences. To change the selected subtitles, you have to override the selection or to set text rack preferred language.

## Accessibility

TrackSelector reads the current state of the accessibility settings for subtitles. It will setup the preferred role and preferred language for text tracks.

**Comment by StaehliJ** [comment]
Implemented.
