### ISSUE TITLE
Basic support for subtitles and audio tracks

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#194]
**As a user** I want to be able to see subtitles and audio tracks available for some content, as well as to select / deselect a track. 

# Acceptance criteria

- An API is provided to list available subtitles and audio tracks.
- An API is provided to list the current subtitle and audio track selection.
- An API is provided to select a track (or remove selection if this makes sense).
- Forced subtitles must not treated in a special way.
- The behavior is correct when no subtitles or audio tracks are available.

# Documentation

See [official documentation](https://developer.android.com/guide/topics/media/exoplayer/track-selection).

# Hints

There is multiple way to select text and audio tracks. One is to override the selection for a given track, the other is to set preferred language or role to the TrackSelector.

# Tasks

- [x] Add API to list available subtitles and audio tracks (forced subtitles not filtered).
- [x] Add API to change the current track selection (basic, no automatic mode).
- [x] Display menu in the demo.
