### ISSUE TITLE
Forced subtitles support

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#195]
**As a user** I want forced subtitles to be automatically enabled when appropriate. I never want to see them or be able to select them directly.

# Acceptance criteria

- Forced subtitles are automatically enabled based on the currently selected audio language.
- Forced subtitles are never returned from usual public player APIs.
- Forced subtitles cannot be selected via the public player API.
- Forced subtitles are not displayed in the demo.

# Documentation

- [Team discussion](https://github.com/SRGSSR/pillarbox-documentation/issues/44).
- https://developer.apple.com/library/archive/releasenotes/AudioVideo/RN-AVFoundation/index.html#//apple_ref/doc/uid/TP40010717-CH1-DontLinkElementID_3
- https://github.com/videojs/http-streaming/pull/1329

# Hints

TrackSelector can select the correct forced text track based on the preferred language or default audio track selected, but not if the user overrides the audio track. Should we handle this use cases?

# Tasks

- [ ] Filter forced subtitles from subtitle lists.
- [ ] Ensure forced subtitles cannot be selected from the public API, even if they were retrieved in some other way (e.g. directly from the queue player asset).
- [ ] Automatically enable forced subtitles based on the currently selected audio language, when no subtitle track has been explicitly selected.
