### ISSUE TITLE
Basic playback for unprotected content

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#20]
As a user I want to play all type of unprotected audio & video streams provided by SSR SRG. 

# Acceptance criteria

- Demo available to play these streams
    - Video
        - On-Demand
        - Live
        - Live with DVR
    - Audio
        - On-Demand
        - Live
        - Live with DVR
- Display Play / Pause buttons
- Seek in the content for On-Demand & Live with DVR
- Protected content (DRM / Token) not included during this support of stream
- No timestamp management
- No local (download) playback management

# Tasks

- [ ] Create .json for all stream use cases
- [ ] Create a demo item json loader
- [ ] Demo scaffolding with top level navigation
- [ ] Add "Tab" for streams showcases
- [ ] Add settings, currently only showing library version.
