### ISSUE TITLE
Update to Material 3

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#212]
**As a integrator** I want to use Pillarbox-UI with material3.

# Acceptance criteria

- Pillarbox UI module doesn't have material dependencies.
- The demo is migrated to material3

# Tasks

- [ ] Use BOM for compose version management.
- [ ] Remove pillarbox-ui material dependencies.
- [ ] Migrate Pillarbox demo to material 3.

In order to prepare TV integration, it is recommended to migrate to Material3 as TV compose ui is based on material3.
