### ISSUE TITLE
Add user consent

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#233]
**As a SRG SSR executive** I want user consent management to be implemented consistently in all SRG SSR mobile and TV products.

# Acceptance criteria

- User consent can be changed at any time.
- The agreed user consent service list is sent to Commanders Act with each event in `consent_services`, formatted according to the documentation.
- The user consent is sent to comScore as described in the documentation 2.5.0.

# Hints

- [Documentation](https://confluence.srg.beecollaboration.com/display/SRGPLAY/Project+-+User+consent).
- [Similar issue for SRG Letter](https://github.com/SRGSSR/srgletterbox-android/pull/449).

# Tasks

**Task list draft, a team discussion is still needed**

- [ ] Add permanent parameters to CommandersAct
- [ ] Add permanent parameters to comScore.
- [ ] Send user consent to Commanders Act in `consent_services`.
- [ ] Send user consent to comScore (likely according to the implementation guide, section 2.5).
