### ISSUE TITLE
Improve error with localized message

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#249]
**As a user / integrator** I want to display a localized message to the user when `PillarboxPlayer` send an error,.

# Acceptance criteria

- Specific core business error are localized in french, german, romanch, english and italian.

# Tasks

- [ ] Add string.xml to core business module
- [ ] Add french, german, italian and romanch translations.
- [ ] Defaut string.xml will be english.
