### ISSUE TITLE
Android TV Demo

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#255]
**As a user / integrator** I want to test Pillarbox on my Android TV device.

# Acceptance criteria

- PillarboxDemo is runnable on TV.
- All video content from the SRG SSR are playable.
- Display samples pages as a list.
- Display a minimal player without toggleable controls.

# Tasks

- [x] Add android TV module
- [x] Shared demo module
- [ ] TV home screen as a List
- [x] TV player with leanback, on item is using the default leanback "player".
- [x] TV player written with compose.
- [x] TV controls
- [ ] Pretty UI
