### ISSUE TITLE
Compose toggleable view for TV and Mobile

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#259]
**As a user / integrator**  I want a composable like AnimatedVisibility that hide automatically after a delay.

# Acceptance criteria

- Toggleable view is working on Android TV and Mobile.
- View can be toggled from a click or a key event.
- A public api to set the delay and the visibility state.

# Tasks

- [ ] Create a state object
- [ ] ToggleView using state object
- [ ] Preview composable
- [ ] Implements on android tv and mobile demo player
- [ ] Android TV controls
- [ ] Mobile controls are usable with keyboard too
- [ ] Check accessibility

**Comment by StaehliJ** [comment]
# Accessibility

In compose we can get LocalAccessibilityManager that have a method to compute ideal timeout. After some experimentation, it make duration 3 times greater.

```
val manager = LocalAccessibilityManager.current
    val durationWithAccessibility = manager?.let {
        it.calculateRecommendedTimeoutMillis(
            duration.inWholeMilliseconds,
            containsIcons = true,
            containsText = true,
            containsControls = true
        ).milliseconds
```

The `maintainVisibleOnFocus` seems to not working with TalkBack.
