### ISSUE TITLE
Improve Demo with some "polish"

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#263]
**As a user / integrator** I want to have the wow effect when launching the Pillarbox demo android.

# Acceptance criteria

- Consistency between top level views
- Demo are easy to understand
- Demo is usable in landscape mode

# Tasks

- [x] Rework demo player view
- [x] Update navigation bar icons
- [x] Align each home view by using same item view if possible
- [x] Story layout with page indicator and more fullscreen experience
- [x] ~~In landscape use left navigation rail instead of bottom navigation~~
- [x] ~~Make top title has a "sticky header"~~
- [x] ~~Use two pane when in landscape in the search section~~
- [x] Remove system ui controller accompanist dependency
- [x] Fix showcases - Tracking toggle sample in landscape
- [x] Improve playlist demo
- [x] Handle night mode

**Comment by StaehliJ** [comment]
# Fullscreen
The compose system ui controller used in the demo is depreciated : https://google.github.io/accompanist/systemuicontroller/

FullScreen can be handle in a lot of different ways.
- https://developer.android.com/develop/ui/views/layout/immersive
- https://developer.android.com/develop/ui/views/layout/edge-to-edge
- https://developer.android.com/jetpack/compose/layouts/insets

**Comment by StaehliJ** [comment]
# Main navigation in landscape

The usage of a navigation rail is not satisfying enough, plus apple team doesn't nothing special when in landscape mode.

**Comment by StaehliJ** [comment]
# Two pane search

As apple team does nothing when in landscape mode, we also do nothing. The result on tablet is good enough
