### ISSUE TITLE
Play unprotected SRG SSR contents from URNs

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#27]
**As an integrator** I want to be able to play any unprotected Play SRG content via its URN.

# Acceptance criteria

- The API allows content to be played from a URN.
- Production, stage and test environments are supported.
- The first available resource is played (no complicated resolution logic as currently in Letterbox).
- URN-based content is playable from the demo (keep URL-based examples as well).

# Tasks

- [x] Create module pillarbox-core-buisness as discussed [here](https://github.com/SRGSSR/pillarbox-documentation/issues/6#issuecomment-1213193440).
- [x] Integration layer service and data.
- [x] Basic `Resource` filter, take the fist resource.
- [x] Implement `MediaItemSource` using Integration layer
- [x] Fill metadata from `chapter`
- [ ] Update demo with urn

**Comment by StaehliJ** [comment]
The first available resource to played is a too bad criteria. We select the first resource that is "playable" by the Player.
