### ISSUE TITLE
Load DRM / token-protected examples in the demo

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-android#280]
**As a Pillarbox demo user** I want a consistent list of examples between platforms, including those related to DRM or token protected content.

# Acceptance criteria

- The two latest _Top Models_ episodes are playable from the _Examples_ tab.
- The two latest RTS livecenter sports streams are playable from the _Examples_ tab.

# Hints

- Check the Apple Pillarbox demo.

# Tasks

- [x] Create examples viewmodel
- [x] Load the two latest media for the show `urn:rts:show:tv:532539`
- [x] Load the two latest sport stream
