### ISSUE TITLE
Remove complexity

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#283]
**As a SRGSSR integrator** I want to easily create a `PillarboxPlayer` configured for playing SRGSSR content.

# Acceptance criteria

- Integrators can create a new PillarboxPlayer in a single line.
- it handles SRG content and SRGAnalytics streaming.

# Tasks

- [x] Remove `ExoPlayer.Builder` from `PillarboxPlayer`.
- [x] Add missing parameters to `DefaultPillarbox` that set default values for SRG SSR.
- [x] Update demo.
- [ ] Update doc if needed.
