### ISSUE TITLE
Run tests and linters for all modules

### ISSUE THREAD

**Issue by MGaetan89** [SRGSSR/pillarbox-android#288]
**As a developer** I want every module in the project to be validated by the CI.

# Acceptance criteria

- Every module in the project should have its code quality tools (Android Lint, Detekt) and Unit Tests run by the CI

# Tasks

- [ ] Ensure that Android Lint is run for every modules
- [ ] Ensure that Detekt is run for every modules
- [ ] Ensure that Unit Tests are run for every modules
