### ISSUE TITLE
Basic error reporting

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#31]
**As a user** I want to be informed when playback failed for some reason.

# Acceptance criteria

- Loading an unknown URN ends with a failure.
- Loading a blocked URN send a specific error 
- Attempting to play a content without network available fails with an error.
- The user is presented with a basic message informing them about the error.

# Tasks

- [x] Ensure media player errors are correctly reported.
- [x] Ensure media source errors are correctly reported.
- [x] Handle basic block reason error
- [x] Handle resource not found ie Chapter.listResource is empty or no compatible Resource find.
- [x] Display basic error message.
