### ISSUE TITLE
Convert demo to Compose

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#33]
**As a user** I can enjoy the pillarbox demo written is Android Compose.

# Acceptance criteria

-  The demo need to have at least the same fonctionnality has before
-  The demo need to show how playlist are working with all kind of content

# Tasks

- [x] Configure project with Compose
- [x] Create the livestream view with Compose
- [x] Setup the main navigation with compose
- [x] Create a basic player with Compose using ExoplayerView
