### ISSUE TITLE
Akamai token-protected content

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#34]
**As a user** I want to be able to play token-protected content, e.g. streams from the SwissTXT livecenter.

Remark: RSI resources are declared to require an Akamai token but in fact don't.

# Acceptance criteria

- SwissTXT livecenter streams can be played.

# Tasks

- [ ] Add Token provider
- [ ] Exoplayer DataSource using TokenProvider
- [ ] Update Player allowing injecting a custom DataSource
- [ ] Add example to demo (if a long-living example exists).

**Comment by StaehliJ** [comment]
Akamai Token are handle threw a `DataSource` from Exoplayer that allow use to do some logic before open a url.
