### ISSUE TITLE
Make project build on Windows

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#349]
**As a integrator** I want to check out git repository and build the project on Windows.

# Acceptance criteria

- Project repository can be check out on Windows
- Project can be build on Windows

# Tasks

- [x] Rename some assets that can't exist on windows` for example urn:xxx:1234.json`
- [x] Check git hook can be executed
- [x] Project can be build
- [x] Git commit and push can be done
