### ISSUE TITLE
DRM-protected content

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#35]
**As a user** I want to be able to play DRM-protected content, e.g. TV livestreams.

# Acceptance criteria

- Livestreams and TV series play fine.

# Tasks

- [x] Parse DRM information in `Resource`
- [x] Setup `MediaItem` DRM configuration
- [x] Update basic resource selector
- [ ] Add TV livestream examples to demo.
- [ ] Check behavior with simulated slow network (see #81).
- [ ] Check behavior in playlists.
- [ ] Check AirPlay behavior.
