### ISSUE TITLE
Add playlist to the demo

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#39]
**As a user** I can try playlist inside the demo

# Acceptance criteria

- Add demo with "the rencard" use the same as apple project

# Tasks

- [ ] Add playlist tab
- [ ] Add "story like" playlist
- [ ] Add playlist with all demo content
