### ISSUE TITLE
Refactoring SRG content loading

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#455]
**As a integrator** I want to easily play mixed content like urls and SRG contents.

# Acceptance criteria

- Adding additional custom supported content is easier.
- SRG content are created with a mime_type and an uri formatted with the url of the media composition.
- SRG content can load prod, stage content in the same player.

# Tasks

- [ ] Remove custom loading media item from Pillarbox and create directly a MediaSource threw suspend function.
- [ ] Improve adding MediaSource.Factory to Pillarbox.
- [ ] Provide default factory for SRG
