### ISSUE TITLE
Integration with MediaSession

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#49]
**As a user** I can change the playback outside the applications.

# Acceptance criteria

- Playback can be change from "Media Controller center"
- Playback can be changed from a connected bluetooth device.

# Tasks

- [x] Use Media3 MediaSessions
- [x] Update demo with a button to enable background playback
- [x] Add Picture in picture integration

**Comment by StaehliJ** [comment]
You can see the MediaSession is working when

- Media output on the device displays something and can interact with playback state
- Your bluetooth connected device can retrieve media informations and interact with playback state (for exemple samsung watch)
- The picture in picture "controls" display the media controls.
