### ISSUE TITLE
Media notification

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#51]
**As a user** I can display a media style notification.

# Acceptance criteria

- Display a Media notification
- Display lockscreen notifications

# Tasks

- [ ] Add image url to mediaItem
- [ ] Link Notification to MediaSession
- [ ] Update demo with MediaSession and notification
