### ISSUE TITLE
Background Playback Service

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#53]
**As a user** I can play video or audio in background without interruption.

# Acceptance criteria

- Audio and video don't stop when applications is put in background
- Playback continue on Android auto

# Tasks

- [x] Create service to handle background playback and MediaNotification
- [x] MediaSessionService basic class that handle MediaSession and Player
- [x] MediaLibraryService basic class that handle MediaSession and Player
- [x] Add MediaLibraryService to the demo

**Comment by StaehliJ** [comment]
## Handling background playback 

Playback is interrupted while in background after 1min even with network lock if not using Picture in picture or a Service.
To avoid this there is 3 possibilities.

1. Create a Foreground service with MediaSession and Notification for a given Player.
2. Using the official recommendation from Android with a `MediaSessionService` and a `MediaController`
3. We need integration with Android Auto / Automotive, when we have to use a `MediaLibraryService` and a `MedidaBrowser`

### 1. Custom service

Pros:

- Full control of the implementation and the service.
- Can use directly `PillarboxPlayer`.
- Could be enough if android Auto is not needed.

Cons:

-  Not the recommended way to do background playback according to Android Media3 library team.
- If the service doesn't create the Player who has de responsabilities to release it?
- Playback can't start if the application is not open.

### 2. MediaSessionService

Pros: 

- Fully integrated with Android using the recommended way to do background playback.
- No need to keep a _ServiceConnection_ to make the service alive.
- Playback can be started even if the application is not open.

Cons: 

- Have to use `MediaController` to manipulate playback inside the app. `PillarboxPlayer` is only used inside the service.
- Some properties of `MediaItem` are not serialized when using `MediaController`. For exemple `MediaItem.tag`

### 3. MediaLibraryService

Same pros and cons as MediaSessionService. It handles query seach and provide content to applications and by extension Android Auto.

If integrator target Android Auto, it is the way to go!
