### ISSUE TITLE
Compose ExoPlayerView

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#55]
**As a user** I can integrate the `PlayerView` from Exoplayer (Media3) in Compose.

# Acceptance criteria

- Can display PlayerView with Compose
- Player controls can be enable/disable
- Resize mode can be set
- ErrorMessage provider can be customized

# Tasks

- [x] Create a UI module
- [x] PlayerView compose function
- [x] PlayerView customizable
- [x] Handle keep on screen with compose
- [x] Demo with resizable player view
- [x] Add controls view toggle button

**Comment by StaehliJ** [comment]
Performance issue (OOM Exception) come from the custom LoadControl.

**Comment by StaehliJ** [comment]
Keep on screen only when user want it and when player is playing

**Comment by StaehliJ** [comment]
Keep screen on is a Composable parameters. Player state won't change keep screen on.
