### ISSUE TITLE
Update Playlist demo

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#57]
**As a user** I can play with the player playlist

# Acceptance criteria

- User can play with the playlist in the demo
- Items can be moved inside the playlist

# Tasks

- [x] Split current playlist and library items
- [x] Add move button
- [x] Add remove from playlist button
- [x] Shuffle mode
