### ISSUE TITLE
Update Pillarbox documentation

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#571]
**As a integrator** I can have access to documentation regarding chapter, credits and blocked time interval.

# Acceptance criteria

- Chapters and Credits are documented in the player module
- How to make an AssetLoader
- MediaItemTracker up to date
- MediaSession doc inside a separate file

# Tasks

- [x] Chapters and Credits are documented in the player module
- [x] How to make an AssetLoader
- [x] MediaItemTracker up to date
- [x] MediaSession doc inside a separate file
