### ISSUE TITLE
Add apple stream to the demo

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#58]
**As a user** I can play Apple official stream inside the demo.

# Acceptance criteria

- Add apple stream like on Pillarbox-apple demo.

# Tasks

- [x] Remove .json from the demo
- [x] Create demo content inside code
- [x] Add Apple basic and advanced sample
