### ISSUE TITLE
Basic metrics collector UI

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-android#639]
**As a developer** I need to be able to check metrics during playback, in a basic way. **As an encoding / packaging team member** I would like to be able to check metrics of streams I deliver (or test before delivery).

# Acceptance criteria

- A basic textual debugging overlay displays interesting metrics about content being played.
- The overlay can be enabled and configured with Preferences.

# Tasks

- [ ] Compose overlay to display metrics.
- [ ] Add preferences to the bottom navigation.
- [ ] Create a Preference (fragment/activity).
