### ISSUE TITLE
State player view model

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#69]
# Definition

Simplify listening Player events with compose by observing "states". Theses states will be _kotlin flows_.

# Acceptance criteria

- Integrator can "observe" state with Flow
- Make simple extension to retrieve value in Compose

# Tasks

- [x] Flowable states object
- [x] Expose isPlaying
- [x] Expose isLoading
- [x] Expose PlaybackState
- [x] Expose current position (periodic update and player.currentPosition)
- [x] Expose duration
- [x] Expose Seekable
- [ ] Expose isLive
- [x] Simple Compose controls
- [x] UnitTests

**Comment by StaehliJ** [comment]
isLive not done in this issue.
