### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#74]
**As a user** it is boring to receive a nightly every time a pr is updated.

# Acceptance criteria

- Build nightly automatically only every night if main has changed.
- Allow manually triggering a nightly on any branch.

# Tasks

- [x] Change github actions for nightly build
- [x] Fix VERSION reading for releases
- [x] Add a RELEASENOTES.md to the repository.

**Comment by StaehliJ** [comment]
We won't create a RELEASENOTES.md until it can be done automatically. To avoid copy past.

**Comment by StaehliJ** [comment]
Trigger Nightly every nights if some commits happend last 24h.
