### ISSUE TITLE
Improve demo with a playlist ui

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#77]
Improve the demo with a widget for managing the current playlist.
With a library of playable possible items. This library will be the same as for the Auto app demo.

# Acceptance criteria

- Demo user can play with playlists inside the demo.

# Tasks

- [x] Current playlist widget.
- [x] Media library widget.
- [x] A demo player with this widget.
- [x] Remove accompagnist pager as it was officially released with compose
