### ISSUE TITLE
Cleanup demo

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#79]
**As a user or an integrator** I want to easily understand the demo.

Currently the demo is a bit messy with a lot of Player and player view. The idea is to only use one player inside the whole demo. For specific demo, a new player instance would be created.

**Specifics demos:**
- Multi players demo
- Stories player demo
- Minimal simple player demo in a separate Activity to show the simple way to do playback.

# Acceptance criteria

- Use the MediaLibraryController as "main player"

# Tasks

- [x] Rename tabs ("Examples","showcases","informations").
- [x] Showcase : Layout (story, normal).
- [x] Showcase : Playlists (with player with playlist management).
- [x] Showcase : Embeding (Player swap, multi player).
- [x] Showcase : Exoplayer UI with Pillarbox, MediaController (auto) sample.
- [ ] Use MediaLibraryController as Player for all demo.
- [x] ShowCases view
