### ISSUE TITLE
Implement CommanderActs V5 tracker

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#87]
**As a user / integrator** I can use official CommanderActs stream tracker like done on SRGLetterbox

# Acceptance criteria

- Tracker tracks media event like on SRGLetterbox

# Tasks

- [x] Create a TagCommander delegate for sending abstract data.
- [x] Implement TagCommander Tracker.
- [x] Add stop reason to `MediaItemTracker.stop`
- [x] MEDIA_POSITION in seconds is round to the upper int. (29.856 => 30)

**Comment by StaehliJ** [comment]
CommandersAct have to now the stop reason, if the stop is stop because the media reach the end of the file or because user stop the playback. Stopping the playback when
- release the player
- seekToNext or Previous item
- stop the player

For EoF when
- item auto transition to the next
- player reach the playback state Player.STATE_ENDED
- item repeat
