### ISSUE TITLE
Tracker activation flag

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#89]
**As a integrator** I need to be able to enable or disable some trackers when not needed (e.g. in a multi-instance context).

# Acceptance criteria

- A tracker can be disabled or enabled when needed.
- It is possible to have only some trackers disabled (maybe no work required; tracker implementations could ignore enable / disable requests if they need to be always enabled).

# Tasks

- [x] Each `Player` instance provides a way to enable or disable analytics for associated trackers.
- [x] Update tracker lifecycle methods if needed.
- [ ] Implement an example of a tracker which is never disabled (e.g. diagnostics for QoS).
