### ISSUE TITLE
SRG SSR hidden and page view event tracking support

### ISSUE THREAD

**Issue by StaehliJ** [SRGSSR/pillarbox-android#90]
**As an app developer integrating Pillarbox** I want to be able to track page views according to the SRG SSR standards. I also want to be able to track various arbitrary events.

# Acceptance criteria

- Page view analytics are correctly collected in the demo.
- Hidden tracking is possible.

# Hints

Identifiers do not need to be made private as they can be sniffed easily and are publicly visible on GitHub since years anyway.

# Tasks

- [x] Implement page view analytics for comScore.
- [x] Implement page view analytics for Commanders Act.
- [x] Implement hidden event analytics for Commanders Act.
- [x] Handle user id
- [ ] Handle from push notifications
- [x] Add Unit tests

**Comment by StaehliJ** [comment]
Should we still send page id build client side?

**Comment by StaehliJ** [comment]
nonLocalizedApplicationName was used in witch case?

The use case is when you localized the application name but for analytics we only need one application name. The case PLAY is not concerne with that because the application is "localized" but each version is a real analytics application name.

**For example**

```
AnalyticsName : MySRG
FR : Mon SRG
DE : Meine SRG
IT: Magica SRG
```
